# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md

footer: 'follow me on <a href="http://reddit.com/u/c43211/">Reddit</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
